// Introduction order: the fixed order in which never-seen items enter
// sessions. Generated by rule from layout data; no state, no clock.

import { Note } from 'tonal';

import type { Instrument } from '../data/index';
import type { Direction, QuizDirection, Side } from './session';
import { flattenGrid, itemKey, layoutGrid } from './session';

// Fixed constant, not a setting: how many buttons the home cluster holds.
const HOME_CLUSTER_SIZE = 6;

// The home cluster gathers the naturals sounding nearest this pitch: middle C
// on the right side, C3 on the left.
const HOME_ANCHOR_MIDI: Record<Side, number> = { right: 60, left: 48 };

interface Button {
  row: number;
  column: number;
  // The layouts this position has a pitch in; both, on aligned grids.
  directions: Direction[];
  // The opening pitch is the reference for the home cluster, pass membership,
  // and ties.
  midi: number;
}

export type GridPosition = [row: number, column: number];

// Hand-tuned home clusters per instrument and side; the spiral grows from one
// of these instead of the generated cluster. Ships empty: no pedagogy source
// names concrete starting buttons.
export const homeClusterOverrides: Record<string, Partial<Record<Side, GridPosition[]>>> = {};

export interface IntroductionOptions {
  instrument: string;
  layouts: Instrument;
  quizDirection: QuizDirection;
  overrides?: typeof homeClusterOverrides;
}

// One physical button = one grid position across both directions. A position
// present in only one direction's grid (misaligned data) yields just the item
// it has, judged by that pitch, so no item is ever left out of the order.
function sideButtons(layouts: Instrument, side: Side): Button[] {
  const byPosition = new Map<string, Button>();
  for (const direction of ['open', 'close'] as const) {
    for (const { row, column, pitch } of flattenGrid(layoutGrid(layouts, side, direction))) {
      const midi = Note.midi(pitch);
      if (midi === null) throw new Error(`unreadable pitch ${pitch} at ${side} ${row}/${column}`);
      const button = byPosition.get(`${row}/${column}`);
      if (button) button.directions.push(direction);
      else byPosition.set(`${row}/${column}`, { row, column, directions: [direction], midi });
    }
  }
  return [...byPosition.values()].sort((a, b) => a.row - b.row || a.column - b.column);
}

function homeCluster(buttons: Button[], side: Side): Button[] {
  const anchor = HOME_ANCHOR_MIDI[side];
  return [...buttons]
    .sort((a, b) => Math.abs(a.midi - anchor) - Math.abs(b.midi - anchor) || a.midi - b.midi)
    .slice(0, HOME_CLUSTER_SIZE);
}

// Idealized button lattice: columns one unit apart, rows ROW_GAP apart, odd
// rows exactly half a column to the left. The keyboard draws roughly this;
// its rendering choices (an arc, centering, a wide-layout squeeze, a 40/79
// stagger) are left out so equally near neighbors tie exactly and the lower
// pitch decides.
const ROW_GAP = 60 / 79;
const TIE_EPSILON = 1e-9;

function squaredDistance(a: Button, b: Button): number {
  const dx = a.column - (a.row % 2) / 2 - (b.column - (b.row % 2) / 2);
  const dy = (a.row - b.row) * ROW_GAP;
  return dx * dx + dy * dy;
}

function distanceToRegion(button: Button, region: Button[]): number {
  return region.length ? Math.min(...region.map((b) => squaredDistance(button, b))) : 0;
}

// Proximity spiral: repeatedly take the candidate nearest the introduced
// region, ties to the lower pitch, growing the region as it goes.
function spiral(region: Button[], candidates: Button[]): Button[] {
  const introduced = [...region];
  const remaining = [...candidates];
  const order: Button[] = [];

  while (remaining.length > 0) {
    let best = 0;
    let bestDistance = distanceToRegion(remaining[0], introduced);
    for (let i = 1; i < remaining.length; i++) {
      const distance = distanceToRegion(remaining[i], introduced);
      const nearer = distance < bestDistance - TIE_EPSILON;
      const tied = Math.abs(distance - bestDistance) <= TIE_EPSILON;
      if (nearer || (tied && remaining[i].midi < remaining[best].midi)) {
        best = i;
        bestDistance = distance;
      }
    }
    const [next] = remaining.splice(best, 1);
    order.push(next);
    introduced.push(next);
  }

  return order;
}

// C-major scale degrees by sound, so spelling never matters (E# is a natural).
const NATURAL_CHROMAS = new Set([0, 2, 4, 5, 7, 9, 11]);

function isNatural(button: Button): boolean {
  return NATURAL_CHROMAS.has(button.midi % 12);
}

function overriddenCluster(buttons: Button[], positions: GridPosition[], side: Side): Button[] {
  return positions.map(([row, column]) => {
    const button = buttons.find((b) => b.row === row && b.column === column);
    if (!button)
      throw new Error(`home-cluster override names an empty cell: ${side} ${row}/${column}`);
    return button;
  });
}

// One side: the home cluster, then a spiral over the other naturals, then a
// spiral over the accidentals — each measured against everything introduced
// so far.
function sideOrder(layouts: Instrument, side: Side, override?: GridPosition[]): Button[] {
  const buttons = sideButtons(layouts, side);
  const cluster = override
    ? overriddenCluster(buttons, override, side)
    : homeCluster(buttons.filter(isNatural), side);
  const rest = buttons.filter((button) => !cluster.includes(button));
  const naturals = spiral(cluster, rest.filter(isNatural));
  const accidentals = spiral(
    [...cluster, ...naturals],
    rest.filter((button) => !isNatural(button)),
  );
  return [...cluster, ...naturals, ...accidentals];
}

// Sides interleave per button, right first; each button's close item follows
// its open item immediately.
export function introductionOrder(options: IntroductionOptions): string[] {
  const { instrument, layouts, quizDirection, overrides = homeClusterOverrides } = options;
  const sides: [Side, Button[]][] = [
    ['right', sideOrder(layouts, 'right', overrides[instrument]?.right)],
    ['left', sideOrder(layouts, 'left', overrides[instrument]?.left)],
  ];
  const keys: string[] = [];

  const longest = Math.max(...sides.map(([, buttons]) => buttons.length));
  for (let i = 0; i < longest; i++) {
    for (const [side, buttons] of sides) {
      const button = buttons[i];
      if (!button) continue;
      for (const direction of button.directions) {
        keys.push(itemKey(instrument, side, direction, button.row, button.column, quizDirection));
      }
    }
  }

  return keys;
}
