# /// script
# requires-python = ">=3.11"
# dependencies = ["fonttools>=4.55"]
# ///
"""Extract the staff-notation glyphs from the Bravura font into src/assets/staffGlyphs.ts.

Run from anywhere: `uv run scripts/extract_staff_glyphs.py [path/to/Bravura.otf]`.
Without an argument the font is downloaded from the steinbergmedia/bravura repo.
The generated module is checked in; rerun only to change the glyph set.
"""

import sys
import tempfile
import urllib.request
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

FONT_URL = "https://raw.githubusercontent.com/steinbergmedia/bravura/master/redist/otf/Bravura.otf"

# SMuFL name -> codepoint (https://github.com/w3c/smufl glyphnames.json)
GLYPHS = {
    "gClef": 0xE050,
    "fClef": 0xE062,
    "noteheadWhole": 0xE0A2,
    "noteheadBlack": 0xE0A4,
    "accidentalFlat": 0xE260,
    "accidentalNatural": 0xE261,
    "accidentalSharp": 0xE262,
}

# SMuFL: 1 staff space = 0.25 em; Bravura has 1000 units/em.
FONT_UNITS_PER_STAFF_SPACE = 250

OUT_PATH = Path(__file__).resolve().parent.parent / "src" / "assets" / "staffGlyphs.ts"


def number_to_string(value: float) -> str:
    return str(int(value)) if float(value).is_integer() else repr(value)


def main() -> None:
    if len(sys.argv) > 1:
        font_path = Path(sys.argv[1])
    else:
        font_path = Path(tempfile.gettempdir()) / "Bravura.otf"
        if not font_path.exists():
            print(f"downloading {FONT_URL}")
            urllib.request.urlretrieve(FONT_URL, font_path)

    font = TTFont(font_path)
    upem = font["head"].unitsPerEm
    if upem != 1000:
        sys.exit(f"expected 1000 units/em, got {upem}")

    # The name-table copyright entry embeds the full OFL text; keep the first line only.
    copyright_notice = font["name"].getDebugName(0).splitlines()[0].strip()
    cmap = font.getBestCmap()
    glyph_set = font.getGlyphSet()
    hmtx = font["hmtx"]

    entries = []
    for name, codepoint in GLYPHS.items():
        glyph_name = cmap[codepoint]
        pen = SVGPathPen(glyph_set, ntos=number_to_string)
        glyph_set[glyph_name].draw(pen)
        d = pen.getCommands()
        advance_sp = hmtx[glyph_name][0] / FONT_UNITS_PER_STAFF_SPACE
        entries.append((name, codepoint, d, advance_sp))

    lines = [
        "// Generated by scripts/extract_staff_glyphs.py — do not edit by hand.",
        "//",
        f"// Glyph outlines extracted from the Bravura music font ({FONT_URL.rsplit('/redist', 1)[0]}).",
        f"// {copyright_notice}",
        "// Licensed under the SIL Open Font License, Version 1.1 (https://openfontlicense.org).",
        '// "Bravura" is a Reserved Font Name; this module is a derived work and is',
        "// therefore not named Bravura.",
        "",
        "/** Font units per staff space (SMuFL: 1 staff space = 0.25 em; 1000 units/em). */",
        f"export const FONT_UNITS_PER_STAFF_SPACE = {FONT_UNITS_PER_STAFF_SPACE};",
        "",
        "export interface StaffGlyph {",
        "  /** SVG path data in font units: baseline-registered, Y axis points up. */",
        "  d: string;",
        "  /** Advance width in staff spaces. */",
        "  w: number;",
        "}",
        "",
        "// A glyph lands on a note's line or space when placed with",
        '// transform="translate(x y) scale(s -s)" where s = staffSpacePx / FONT_UNITS_PER_STAFF_SPACE.',
        "export const staffGlyphs = {",
    ]
    for name, codepoint, d, advance_sp in entries:
        lines.append(f"  // U+{codepoint:04X}")
        lines.append(f"  {name}: {{")
        lines.append(f"    d: '{d}',")
        lines.append(f"    w: {advance_sp:g},")
        lines.append("  },")
    lines += [
        "} as const satisfies Record<string, StaffGlyph>;",
        "",
    ]

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines))
    print(f"wrote {OUT_PATH} ({OUT_PATH.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
